### ISSUE TITLE
Add option for larger images

### ISSUE THREAD

**Issue by JusKillmeQik** [JusKillmeQik/PoE-Leveling-Guide#16]
This may wait until I collect newer information on the layouts as they are outdated

**Comment by grendahl06** [comment]
I run the game in 1080p, and the Tree only shows the upper left part of the image even when I scale the image down to 300 pixels.  Worse, it enlarges the picture to some frame I do not have access to from the .ini file or the settings menu.  Thanks

**Comment by JusKillmeQik** [comment]
How are you generating the tree.jpg in the first place? What folder are you placing the tree.jpg in? Do you mind sending zipping up your leveling-guide folder and sending it to me so I can see if acts the same on my computer? If you can't send me the whole folder, could you send me the tree.jpg file?

The program automatically tries to make the tree take up half of the screen width or height based on it's dimensions. This is so it's big enough to see while you're planning. If I can figure out what yours is doing wrong I can fix it. But generally it's better to have a high res tree instead of only 300 pixels.

**Comment by grendahl06** [comment]
Hi,

I generated the images using the Snipping Tool on my PoB tree; because my
native resolution is 4k, the images started Hi Res.  I play PoE at 1080p
(one-quarter of my PC res) and noticed the images were only showing the
upper left quadrant.  Since then, I first tried just shrinking the image
(which then took a shrunk image and the blew it up while still only showing
the upper left corner), and then second, I tried padding the image
height and width with white space so that my image was only in the upper
left corner (and now it shows the original part of my picture, leaving the
white space offscreen.)  This is using the "Left" option for the image.
When using "Right" it takes only the left half of what would have been
shown.

Let me know if I can provide more details.

In terms of creating this package, I started by copying and pasting one of
the guides that ships with the tool.  I then renamed the folder and
replaced the gems ini (UI editor in tool) and the tree.jpg files for each
of the acts.  I wasn't sure how to do that for maps.

Thanks,
Mike

**Comment by JusKillmeQik** [comment]
would you mind attaching the tree.jpg to this issue so I can see if breaks on my computer as well?

**Comment by grendahl06** [comment]
[Champion.zip](https://github.com/JusKillmeQik/PoE-Leveling-Guide/files/4749338/Champion.zip)
![tree](https://user-images.githubusercontent.com/28264877/84095912-29e95e00-a9c6-11ea-965e-cd6bba4b94a0.jpg)
![tree_original](https://user-images.githubusercontent.com/28264877/84095914-29e95e00-a9c6-11ea-94f5-2ad58bc98fc1.jpg)

I was curious what happens if I'd emailed with the attachments.  Apparently it didn't add them.

I've attached the whole "build" plus two of the images I recently tried

Thanks

**Comment by JusKillmeQik** [comment]
I tested it on my computer and all of the act images worked correctly. Was it just act 4 that was breaking, or did you noticed it in all of the Acts?

Could you send me your config.ini file as well so I can set everything up exactly the same?

**Comment by grendahl06** [comment]
[config.ini.txt](https://github.com/JusKillmeQik/PoE-Leveling-Guide/files/4754961/config.ini.txt)

![image](https://user-images.githubusercontent.com/28264877/84203822-b3a13600-aa6f-11ea-9b50-ace50c9b45ec.png)

I only tried the padding trick in Act IV, but here is that same set from Act VII.  As you can see, only the upper left quadrant comes into view correctly.  Whatever frame is calculating that size is using my PC's resolution instead of the Game's; and then if it's set right, I'm only getting the vertical left side of that quadrant.

Let me know if I can share anything else that might help

**Comment by JusKillmeQik** [comment]
I figured it out!!! It's because you have DPI scaling set to something over 100%. I didn't account for that in the image creation. I have fixed it in the latest patch, but that won't go out until Friday. You can fix it yourself by changing this line in lib/draw.ahk

```Gui, Tree:+E0x20 +E0x80 -Caption +ToolWindow +LastFound +AlwaysOnTop -Resize +DPIScale +hwndTreeWindow```

to 

```Gui, Tree:+E0x20 +E0x80 -Caption +ToolWindow +LastFound +AlwaysOnTop -Resize -DPIScale +hwndTreeWindow```

notice the "-DPIScale"

However, upon further testing, it appears the font size along with the control sizes look very bad with DPI scaling. So I may recommend turning it off while you play PoE. You'll need to restart the leveling guide if you change the DPI settings. I'll see if I can find a better solution before launch, and if not, I'll work on it for the next release.

Thank you for find this and for taking so much time to send me supporting data!

**Comment by grendahl06** [comment]
my pleasure.  I'm glad it proved helpful.  This is a great tool; and I'm really looking forward to using it rather than having PoE and PoB up at the same time when I play.
