### ISSUE TITLE
no layout variations?!

### ISSUE THREAD

**Issue by SheerGeyser** [JusKillmeQik/PoE-Leveling-Guide#39]
![image](https://user-images.githubusercontent.com/56490213/76174295-91212780-61b7-11ea-8924-a3fbde4e7849.png)
![image](https://user-images.githubusercontent.com/56490213/76174336-cded1e80-61b7-11ea-817c-8a9d2e290016.png)
![image](https://user-images.githubusercontent.com/56490213/76174359-e2c9b200-61b7-11ea-8ef9-7c43f8f522f0.png)

**Comment by JusKillmeQik** [comment]
Can you add a little more context? There are three variations for that zone that Engineering Eternity mapped out 2 years ago. Are you saying that the one you generated does not map to one of those variations? They are outdated but no one has taken the task to update them yet. If your problem is something else, I'd be happy to fix it.
