### ISSUE TITLE
Recommended Fixes

### ISSUE THREAD

**Issue by grendahl06** [JusKillmeQik/PoE-Leveling-Guide#52]
Again, thank you for this tool.  These may only be QoL for my setup ;-) but I thought to share them here just in case.

Issue: Controls height too short
sizing.ahk
Line 020: global control_height := 3 * (points+3)
Solution: controls are tall enough to click easily without taking up too much space

Issue: Adding a Passive Tree to maps
draw.ahk
Line 168: no change needed
Solution: create a folder called "Tier 1"

**Comment by JusKillmeQik** [comment]
It my recent updates I have now accounted for DPI when creating the size of elements, so the controls should look better. Please let me know if they are still too small and I can look into it.

Since you can create the Tier 1 folder yourself for your builds, I don't think I'm going to add that myself right now. If I missed something else here, please let me know. For what it's worth, I just put the tree I want to use in maps in my Act 10 folder.
