### ISSUE TITLE
Feature: Add offhand gem leveling

### ISSUE THREAD

**Issue by Hillgrove** [JusKillmeQik/PoE-Leveling-Guide#56]
I find I fiddle a lot with the gem setups, as the build I usually start with  (Kay's Summoner) have you picking up gems to level up, before you need them.

This is no issue in the early levels, but as you start to have several 3 or 4-links, I don't have room to put the gems I need to level up.

Secondly I think it would be a nice addition to have a section to put gems that does not need links.

This way I don't need to use 6 lines in a 6L slot, to show they are individual gems and does not require linking.

**Comment by JusKillmeQik** [comment]
I'm not worried about the gems that don't require linking, since if I added more slots for them it could run off the screen. But you are correct that if you are using every single gem slot and also need 6 gems in your weapon swap there is no place for it. I don't have time to add this before 3.12 but I'll start thinking about how I would redesign this to hold more gems.

**Comment by JusKillmeQik** [comment]
I have added more gems for each slot instead of a specific off hand section. This allows for more notes or gems throughout the leveling process
